/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'intel' at '12/3/17 7:57 PM' with Gradle 2.14.1
 *
 * @author intel, @date 12/3/17 7:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
